// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3cckuM2Yhl7HG5onik6ZOYDvnl_TeW_U',
    appId: '1:481028193913:web:96265d6224bff631c55ea8',
    messagingSenderId: '481028193913',
    projectId: 'chatii-fire',
    authDomain: 'chatii-fire.firebaseapp.com',
    storageBucket: 'chatii-fire.appspot.com',
    measurementId: 'G-ET3CLJLBRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQO8p5DoVfrxoYKVLA9eicKOUiu6eQFKc',
    appId: '1:481028193913:android:05931576baf63cc4c55ea8',
    messagingSenderId: '481028193913',
    projectId: 'chatii-fire',
    storageBucket: 'chatii-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsHo7nOiD5iRJrURWYHLhqVE9n_rk2Pc',
    appId: '1:481028193913:ios:d6d70b2c55978469c55ea8',
    messagingSenderId: '481028193913',
    projectId: 'chatii-fire',
    storageBucket: 'chatii-fire.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRsHo7nOiD5iRJrURWYHLhqVE9n_rk2Pc',
    appId: '1:481028193913:ios:a1a7e1607d4160dec55ea8',
    messagingSenderId: '481028193913',
    projectId: 'chatii-fire',
    storageBucket: 'chatii-fire.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
